### PR TITLE
Fix/inconsistent behaviour with object tap

### PR DESCRIPTION
**Pull request by PikachuEXE**

### CODE REVIEW

**Comment by msievers** [comment]
Travis shows some errors with ruby 1.9. I took a look into it and `public_send` behaves differently for ruby 1.9 and >= 2. Here is an example

``` ruby
class SomeClass
  def call
    public_send :some_protected_method
  end

  protected

  def some_protected_method
    puts "Hello World"
  end
end

SomeClass.new.call
```

For ruby 1.9 this prints `Hello World`, for ruby >=2 it says

```
`public_send': protected method `some_protected_method' called for #<SomeClass:0x00000000ed3910> (NoMethodError)
```

**Comment by msievers** [comment]
One could possibly check if the given method name is included in `public_methods`, but this might introduce some serious performance penalty doing this every time `mighty_tap` is called. Any ideas how to deal with it ?

**Comment by msievers** [comment]
I have incorporated your ideas in b9d4540a6bb640f87ee7573c0e6a0c1713a3dbc6. I tried to be pragmatic in order not to hit performance. `public_send` is used instead of `send`, but the spec for protected methods is only executed on mri rubys >= 2.0.0. 

So it behaves the same like tap for private methods. For protected methods it behaves the same for mri >= 2.0.0. I think this should be a good tradeoff between conformance and performance.

Feel free to reopen an issue if you think this is not sufficient.

**Comment by PikachuEXE** [comment]
I think that's enough since 1.9.3 is EOL.
If they have problem with that then they can open an issue...

**Pull request closed without merging**
